// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using UntisExp;

namespace vplan
{
	public partial class GroupController : UITableViewController
	{
		List<Group> ti;
		Fetcher fetcher;

		static bool UserInterfaceIdiomIsPhone {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
		}

		public GroupController (IntPtr handle) : base (handle)
		{
			fetcher = new Fetcher (Alert, refresh);
			if (UserInterfaceIdiomIsPhone) {
				this.Title = "Klasse";
				this.TabBarItem.Image = UIImage.FromBundle ("second");
			}
		}

		public void Alert (string title, string text, string btn) {
			InvokeOnMainThread (new NSAction (delegate {
				new UIAlertView (title, text, null, btn, null).Show ();
			}));
		}

		public void refresh (List<Data> s) {
			throw new NotImplementedException ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			spinnner.StartAnimating ();
			fetcher.getClasses();
			// Perform any additional setup after loading the view, typically from a nib.
		}

		public void add(Group v1) {
			InvokeOnMainThread (new NSAction (delegate {
				spinnner.StopAnimating ();
				ti.Add (v1);
				if (table == null) {
					table = new UITableView (View.Bounds);
					table.AutoresizingMask = UIViewAutoresizing.All;
					table.Source = new GroupTableSource (ti, this);
					Add (table);
				} else {
					table.Source = new GroupTableSource (ti, this);
					table.ReloadData();
				}
			}));
		}

		public void clear() {
			if (ti != null)
				ti.Clear ();
			InvokeOnMainThread (new NSAction (delegate {
				spinnner.StartAnimating();
				if (table != null) {
					table = null;
				}
			}));
		}

		public void changeView () {
			if (UserInterfaceIdiomIsPhone) {
				this.TabBarController.SelectedIndex = 0;
				this.TabBarController.SelectedViewController = TabBarController.ChildViewControllers [0];
			}
		}
			

		public void refresh(List<Group> v1) {
			InvokeOnMainThread (new NSAction (delegate {
				spinnner.StopAnimating ();
				table.Source = new GroupTableSource (v1, this);
				table.ReloadData();
				ti = v1;
			}));
		}

		protected void CreateTableItems ()
		{
			List<Group> tableItems = new List<Group> ();
			tableItems.Add (new Group ());
			table.Source = new GroupTableSource (tableItems, this);
		}

	}
}
