// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using UntisExp;
using UntisExp.Containers;

namespace vplan
{
	public partial class NewsSuperViewController : UISplitViewController
	{
		UIViewController[] controllers;
		public NewsSuperViewController (IntPtr handle) : base (handle)
		{
			this.Title = "Nachrichten";
			this.TabBarItem.Image = UIImage.FromBundle ("third");
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			controllers = ViewControllers;
			Delegate = new RenaissanceSplitViewDelegate ();
		}
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			SetNeedsStatusBarAppearanceUpdate ();
		}

		public void blackMesa(News incident)
		{
			((NewsItemController)controllers [1]).freshNews (incident);
		}
	}
}
