// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using UntisExp;

namespace vplan
{
	public partial class NewsItemController : UIViewController
	{
		public News theNews;

		public NewsItemController (IntPtr handle) : base (handle)
		{
			//lblTitle.Text = theNews.Title;
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			lblTitle.Text = theNews.Title;
			txtMain.Text = theNews.Content;
			if (theNews.Source.AbsoluteUri.IndexOf (VConfig.url) != -1) {
				lblSource.Text = "Christian-Wirth-Schule";
			} else {
				lblSource.Text = "SR-Blog";
			}
			NSUrl URLWithString = new NSUrl(theNews.Image);
			NSData dataWithContentsOfURL = NSData.FromUrl(URLWithString);
			UIImage myImage = new UIImage(dataWithContentsOfURL, 1.0f);
			imgMain.ContentMode = UIViewContentMode.ScaleAspectFit;
			imgMain.ClipsToBounds = true;
			imgMain.Image = myImage;
		}
	}
}
