// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text;

using Foundation;
using UIKit;

using UntisExp;

namespace vplan
{
	public partial class NewsItemController : UIViewController
	{
		public News theNews;

		public NewsItemController (IntPtr handle) : base (handle)
		{
			this.NavigationItem.SetRightBarButtonItem (
				new UIBarButtonItem ("Zurück", UIBarButtonItemStyle.Done, delegate(object sender, EventArgs e) {
					var initialViewController = Storyboard.InstantiateInitialViewController () as UIViewController;
					NavigationController.NavigationBarHidden = true;
					NavigationController.PushViewController (initialViewController, true);
				}), true);
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			txtMain.Editable = false;
			InitNewsPage ();
			btnMore.TouchUpInside += (object sender, EventArgs e) => {
				try {
					UIApplication.SharedApplication.OpenUrl(new NSUrl(theNews.Source.AbsoluteUri));
				} catch {}
			};
		}
		static bool UserInterfaceIdiomIsPhone {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
		}

		public void InitNewsPage()
		{
			if (theNews != null) {
				lblTitle.Text = theNews.Title;
				txtMain.Text = theNews.Content;
				if (theNews.Source.AbsoluteUri.IndexOf (VConfig.url) != -1) {
					lblSource.Text = "Christian-Wirth-Schule";
				} else {
					lblSource.Text = "SR-Blog";
				}
				NSUrl URLWithString = new NSUrl (theNews.Image);
				NSData dataWithContentsOfURL = NSData.FromUrl (URLWithString);
				UIImage myImage = new UIImage (dataWithContentsOfURL, 1.0f);
				imgMain.ContentMode = UIViewContentMode.ScaleAspectFit;
				imgMain.ClipsToBounds = true;
				imgMain.Image = myImage;
			}
		}
		public void freshNews (News n)
		{
			theNews = n;
			InitNewsPage();
		}
	}
}
