// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace vplan
{
	public partial class RootController : UITabBarController
	{
		public RootController (IntPtr handle) : base (handle)
		{
		}
	}
}
