// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace vplan
{
	public partial class VplanSuperViewController : UISplitViewController
	{
		UIViewController[] controllers;
		public VplanSuperViewController (IntPtr handle) : base (handle)
		{
			this.Title = "Vertretungen";
			this.TabBarItem.Image = UIImage.FromBundle ("first");
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			controllers = ViewControllers;
			Delegate = new RenaissanceSplitViewDelegate ();
		}
		public void highwayToHell ()
		{
			((VplanViewController)controllers [1]).reload ();
		}
	}
}
