// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using System.Collections.Generic;

using Foundation;
using UIKit;

using UntisExp;
using UntisExp.Containers;

namespace vplan
{
	public partial class VplanViewController : UITableViewController
	{
		List<Data> ti;
		List<Igno> ili;
		UIToolbar toolbar;
		Fetcher fetcher;
		PrefManager pm = new PrefManager ();

		static bool UserInterfaceIdiomIsPhone {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
		}

		public VplanViewController (IntPtr handle) : base (handle)
		{
			this.Title = "Vertretungen";
			this.TabBarItem.Image = UIImage.FromBundle ("first");
			fetcher = new Fetcher ();
			fetcher.RaiseReadyToClearView += (sender, e) => {
				clear();
			};
			fetcher.RaiseErrorMessage += (sender, e) => {
				Alert(e.MessageHead, e.MessageBody, e.MessageButton);
			};
			fetcher.RaiseRetreivedScheduleItems += (sender, e) => {
				refresh(e.Schedule);
			};
			ti = new List<Data> ();
			ili = new List<Igno> ();
		}

		public void Alert (string title, string text, string btn)
		{
			InvokeOnMainThread (() => {
				spinnner.StopAnimating();
				new UIAlertView (title, text, null, btn, null).Show ();
			});
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();
			spinnner.StartAnimating ();
			TableView.ContentInset = new UIEdgeInsets (20.0f, 0.0f, 25.0f, 0.0f);
		}
		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			if (UserInterfaceIdiomIsPhone)
				InitVplan ();
		}

		/// <summary>
		/// Shows the button that allows access to the master view popover
		/// </summary>
		public void AddContentsButton (UIBarButtonItem button)
		{
			button.Title = "Contents";
			toolbar.SetItems (new UIBarButtonItem[] { button }, false );
		}

		/// <summary>
		/// Hides the button that allows access to the master view popover
		/// </summary>
		public void RemoveContentsButton ()
		{
			toolbar.SetItems (new UIBarButtonItem[0], false);
		}

		protected void InitVplan()
		{
			int group;
			try {
				int igC = pm.getInt ("ignoredCount");
				try {
					for (int i = igC; i > 0; i--) {
						string igKey = "ignored"+ Convert.ToString(i);
						string value = pm.getString(igKey);
						ili.Add(new Igno(value));
					}
				} catch {}
			} catch {}
			try {
				group = pm.getInt ("group");
				if (group == 0) {
					throw new Exception();
				} else {
					fetcher.GetTimes(group);
				}
			}
			catch {
				if (UserInterfaceIdiomIsPhone) {
					this.TabBarController.SelectedIndex = 2;
					this.TabBarController.SelectedViewController = TabBarController.ChildViewControllers [2];
				} else {
					spinnner.StopAnimating ();
					var li = new List<Data> ();
					li.Add (new Data("Hallo! Wähle eine Klasse, um zu starten."));
					TableView.Source = new TableSource (li);
					TableView.ReloadData ();
				}
			}
		}

		public void reload() {
			spinnner.StartAnimating ();
			InitVplan ();
		}
			
		public void clear() {

			try {
				ti.Clear ();
				TableView.Source = new TableSource (ti);
			} catch {
			}
		}

		public void refresh(List<Data> v1) {
			InvokeOnMainThread (() => {
				for (int i = v1.Count - 1; i >= 0; i--)
				{
					ili.ForEach (delegate (Igno curr) {
						try{
							if (curr.Fach == v1[i].OldSubject && curr.Lehrer == v1[i].Teacher)
								v1.RemoveAt(i);
						} catch {}
					});
				}
				spinnner.StopAnimating ();
				List<Data> _ti = v1;
				if (_ti.Count == 0) {
					_ti.Add(new Data());
				}
				TableView.Source = new TableSource(_ti);
				TableView.ReloadData();
				TableView.AwakeFromNib();
				ti = v1;
			});
		}

		protected void CreateTableItems ()
		{
			List<Data> tableItems = new List<Data> ();
			tableItems.Add (new Data ());
			TableView.Source = new TableSource (tableItems);
		}

	}
}
